# Generated by Django 5.2.5 on 2025-08-27 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.CharField(max_length=1000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Названиие')),
                ('is_active', models.BooleanField(verbose_name='Активен ли')),
                ('discount', models.IntegerField(verbose_name='Скидка %')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_tg', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id аккаунта')),
                ('user_name', models.CharField(max_length=100, verbose_name='Логин')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^(7|8)\\d{10}$')], verbose_name='Номер телефона')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время регистрации')),
                ('ad', models.BooleanField(blank=True, null=True, verbose_name='С рекламы')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('status_1', 'Status 1'), ('status_2', 'Status 2'), ('status_3', 'Status 3')], verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пожелания')),
                ('inscription', models.CharField(blank=True, max_length=20, null=True, verbose_name='Надпись на тортик')),
                ('filling', models.CharField(choices=[('filling_1', 'Filling 1'), ('filling_2', 'Filling 2'), ('filling_3', 'Filling 3')], verbose_name='Статус')),
                ('odred_date', models.DateTimeField(verbose_name='Время заказа')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='admin_bakecake_django.cake', verbose_name='Торт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='admin_bakecake_django.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-odred_date'],
            },
        ),
    ]
