# Generated by Django 5.2.5 on 2025-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bakecake_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото тортика'),
        ),
    ]
