# Generated by Django 5.2.5 on 2025-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bakecake_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odred_date',
            field=models.BooleanField(default=False, verbose_name='Ускоренная доставка'),
        ),
    ]
